services:
  xformconsole:
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - "443:443"
    environment:
      XFORM_SERVICE_ENDPOINT_CRT_PATH: ${XFORM_SERVICE_ENDPOINT_CRT_PATH}
      XFORM_SERVICE_ENDPOINT_KEY_PATH: ${XFORM_SERVICE_ENDPOINT_KEY_PATH}
      XFORM_SERVICE_ENDPOINT_PASSCODE: ${XFORM_SERVICE_ENDPOINT_PASSCODE}
      XFORM_SERVICE_ENDPOINT_USE_CERT: ${XFORM_SERVICE_ENDPOINT_USE_CERT}
      NEXTAUTH_URL: ${NEXTAUTH_URL}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      OKTA_CLIENT_ID: ${OKTA_CLIENT_ID}
      OKTA_CLIENT_SECRET: ${OKTA_CLIENT_SECRET}
      OKTA_ISSUER_PATH: ${OKTA_ISSUER_PATH}
      NEXTAUTH_DEBUG: ${NEXTAUTH_DEBUG}
      NEXT_PUBLIC_OKTA_ISSUER: ${NEXT_PUBLIC_OKTA_ISSUER}
      NEXT_PUBLIC_GA_ID: ${NEXT_PUBLIC_GA_ID}
      XFORM_SERVICE_ENDPOINT: ${XFORM_SERVICE_ENDPOINT}
      XFORM_SERVICE_HEALTHCHECK_URL: ${XFORM_SERVICE_HEALTHCHECK_URL}
      ELASTIC_ENV_TAG: ${ELASTIC_ENV_TAG}
      ELASTIC_HOST: ${ELASTIC_HOST}
      ELASTIC_API_KEY: ${ELASTIC_API_KEY}
      ELASTIC_INDEX: ${ELASTIC_INDEX}
      ELASTIC_INDEX_NGINX: ${ELASTIC_INDEX_NGINX}
    volumes:
      - type: bind
        source: ${SSL_SOURCE}
        target: /ssl
