services:
  xformconsole:
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    environment:
      XFORM_SERVICE_ENDPOINT_CRT_PATH: ${XFORM_SERVICE_ENDPOINT_CRT_PATH}
      XFORM_SERVICE_ENDPOINT_KEY_PATH: ${XFORM_SERVICE_ENDPOINT_KEY_PATH}
      XFORM_SERVICE_ENDPOINT_PASSCODE: ${XFORM_SERVICE_ENDPOINT_PASSCODE}
      NEXTAUTH_URL: ${NEXTAUTH_URL}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      OKTA_CLIENT_ID: ${OKTA_CLIENT_ID}
      OKTA_CLIENT_SECRET: ${OKTA_CLIENT_SECRET}
      NEXTAUTH_DEBUG: ${NEXTAUTH_DEBUG}
      NEXT_PUBLIC_OKTA_ISSUER: ${NEXT_PUBLIC_OKTA_ISSUER}
      NEXT_PUBLIC_GA_ID: ${NEXT_PUBLIC_GA_ID}
      XFORM_SERVICE_ENDPOINT: ${XFORM_SERVICE_ENDPOINT}
      XFORM_SERVICE_HEALTHCHECK_URL: ${XFORM_SERVICE_HEALTHCHECK_URL}
    volumes:
      - type: bind
        source: ${SSL_SOURCE}
        target: /ssl
    networks:
      - izg-shared-network

  nginx:
    build:
      context: ./
      dockerfile: ./nginx/Dockerfile
    ports:
      - 80:80
    networks:
      - izg-shared-network

networks:
  izg-shared-network:
    external: true
